// Auto-generated from client-master.csv
export const CLIENT_MASTER: Record<string, {
  freshbooksId: string | null
  invoiceEmail: string | null
  route: string | null
  distributor: string | null
  packaging: string | null
  active: boolean
}> = {
  'Almond': {
    freshbooksId: "100963",
    invoiceEmail: "rennie@almondnyc.com",
    route: "R31 NL-101",
    distributor: "FS",
    packaging: "Plastic Retail",
    active: true,
  },
  'Astro\'s Pizza': {
    freshbooksId: null,
    invoiceEmail: null,
    route: "R31 NL-196",
    distributor: "FS",
    packaging: "Wholesale",
    active: true,
  },
  'Babylon Farmers Market': {
    freshbooksId: null,
    invoiceEmail: null,
    route: "LI",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Banter - Greenwich Village': {
    freshbooksId: "312191",
    invoiceEmail: "banterholdingsinc@bill.com",
    route: "ND1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Banter - Murray Hill': {
    freshbooksId: "314453",
    invoiceEmail: "banterholdingsinc@bill.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Banter - West Village': {
    freshbooksId: "314451",
    invoiceEmail: "banterholdingsinc@bill.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Bellhop NYC': {
    freshbooksId: "329877",
    invoiceEmail: "elvis@chicadon.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Brightwaters Inn': {
    freshbooksId: "236121",
    invoiceEmail: "marie@bwibar.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Plastic",
    active: true,
  },
  'Canoe Place Inn': {
    freshbooksId: "234018",
    invoiceEmail: "MManjuck@unionsquareevents.com",
    route: "R31 NL-201",
    distributor: "FS",
    packaging: "Wholesale",
    active: true,
  },
  'Chez Ma Tante': {
    freshbooksId: "300757",
    invoiceEmail: "billings@chezmatantebk.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Chica & The Don': {
    freshbooksId: "306773",
    invoiceEmail: "elvis@chicadon.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Coastal Kitchen': {
    freshbooksId: "194008",
    invoiceEmail: "coastalkitchenbookkeeper@gmail.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Plastic",
    active: true,
  },
  'Corey Creek Taproom': {
    freshbooksId: "242920",
    invoiceEmail: "accounting@bedellcellars.com",
    route: "R42 NL-228",
    distributor: "FS",
    packaging: "Wholesale",
    active: true,
  },
  'Drai\'s Supper Club': {
    freshbooksId: "349051",
    invoiceEmail: "accounting@draisnyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Dream Downtown': {
    freshbooksId: "331655",
    invoiceEmail: "Jose.Florentino@taogroup.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Edition Times Square': {
    freshbooksId: "199795",
    invoiceEmail: "apclerk@jfrestaurants.com",
    route: "MID",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Evelyn Hotel': {
    freshbooksId: "275623",
    invoiceEmail: "melrose@kitchensync.us",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Falu House': {
    freshbooksId: "302441",
    invoiceEmail: "hej@faluhouse.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Fini Barclays': {
    freshbooksId: null,
    invoiceEmail: null,
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Fini Patio Bar': {
    freshbooksId: null,
    invoiceEmail: null,
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Fini Pizza': {
    freshbooksId: "284083",
    invoiceEmail: "invoice@finipizza.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'FreshDirect': {
    freshbooksId: "212149",
    invoiceEmail: "ap_esker@freshdirect.com",
    route: "SB4",
    distributor: "ALLNP",
    packaging: "Plastic Retail",
    active: true,
  },
  'Gertie': {
    freshbooksId: "349311",
    invoiceEmail: "gertie@support.getmyfixe.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Gertrude\'s': {
    freshbooksId: "335023",
    invoiceEmail: "gertrudes@support.getmyfixe.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Grey Dog - Chelsea': {
    freshbooksId: "312875",
    invoiceEmail: "peter.adrian@thegreydog.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Grey Dog - Columbus Circle': {
    freshbooksId: "349149",
    invoiceEmail: "peter.adrian@thegreydog.com",
    route: "B1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Grey Dog - Flatiron': {
    freshbooksId: "312877",
    invoiceEmail: "peter.adrian@thegreydog.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Grey Dog - Nolita': {
    freshbooksId: "312879",
    invoiceEmail: "peter.adrian@thegreydog.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Grey Dog - Union Square': {
    freshbooksId: "312881",
    invoiceEmail: "peter.adrian@thegreydog.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Grey Dog - West Village': {
    freshbooksId: "312883",
    invoiceEmail: "peter.adrian@thegreydog.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Holy Cow - Jersey City': {
    freshbooksId: "332303",
    invoiceEmail: "holysquad4@gmail.com",
    route: "B9",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Holy Cow - LES': {
    freshbooksId: "341065",
    invoiceEmail: "holyburgerles@gmail.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Holy Cow - Midtown': {
    freshbooksId: "331481",
    invoiceEmail: "holycowmidtown@gmail.com",
    route: "B1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Holy Cow - Mt Vernon': {
    freshbooksId: "330841",
    invoiceEmail: "holycowwestchester@gmail.com",
    route: "CT",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Ketchy Shuby': {
    freshbooksId: "255398",
    invoiceEmail: "sebastien.lefavre@ketchyshubynyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Legasea': {
    freshbooksId: "312589",
    invoiceEmail: "ian.staley@taogroup.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - 18th Street': {
    freshbooksId: "344921",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - 55th & Madison': {
    freshbooksId: "349393",
    invoiceEmail: "ap@mamannyc.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Ardmore': {
    freshbooksId: "349259",
    invoiceEmail: "ap@mamannyc.com",
    route: "B6",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Broadway': {
    freshbooksId: "349769",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Bryant Park': {
    freshbooksId: "230700",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Cobble Hill': {
    freshbooksId: "349261",
    invoiceEmail: "ap@mamannyc.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Grand Central': {
    freshbooksId: "349391",
    invoiceEmail: "ap@mamannyc.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Greenpoint': {
    freshbooksId: "349273",
    invoiceEmail: "ap@mamannyc.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Greenwich': {
    freshbooksId: "349275",
    invoiceEmail: "ap@mamannyc.com",
    route: "CT",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Hudson': {
    freshbooksId: "347793",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Jersey City': {
    freshbooksId: "349255",
    invoiceEmail: "ap@mamannyc.com",
    route: "B9",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - King': {
    freshbooksId: "347789",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Lexington': {
    freshbooksId: "349283",
    invoiceEmail: "ap@mamannyc.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Lincoln Square': {
    freshbooksId: "349281",
    invoiceEmail: "ap@mamannyc.com",
    route: "ZAB",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Long Island City': {
    freshbooksId: null,
    invoiceEmail: "ap@mamannyc.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Meatpacking': {
    freshbooksId: "347795",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Midtown East': {
    freshbooksId: "349291",
    invoiceEmail: "ap@mamannyc.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Moynihan Station': {
    freshbooksId: "349289",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Nomad': {
    freshbooksId: "347803",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Princeton': {
    freshbooksId: "349267",
    invoiceEmail: "ap@mamannyc.com",
    route: "NJT",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Rockefeller': {
    freshbooksId: "349285",
    invoiceEmail: "ap@mamannyc.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Soho': {
    freshbooksId: "347801",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Tribeca': {
    freshbooksId: "347797",
    invoiceEmail: "ap@mamannyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Upper East Side': {
    freshbooksId: "349277",
    invoiceEmail: "ap@mamannyc.com",
    route: "ZAB",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Upper West Side': {
    freshbooksId: "349279",
    invoiceEmail: "ap@mamannyc.com",
    route: "ZAB",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Washington Square': {
    freshbooksId: "347805",
    invoiceEmail: "ap@mamannyc.com",
    route: "ND1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Maman - Westport': {
    freshbooksId: "349269",
    invoiceEmail: "ap@mamannyc.com",
    route: "CT",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun': {
    freshbooksId: "257120",
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Banquet': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Bow & Arrow': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Bow & Arrow 2': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Club Lounge': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Crafty Slice': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Earth Lounge': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Employee Dining Room': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Kitchen Administration': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Novelle': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Room Service': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Sky Bakeshop': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Sportsbook': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Sportsbook 2': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Sportsbook 3': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Tao': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Todd English': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Todd English 2': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Mohegan Sun - Todd English Tuscany': {
    freshbooksId: null,
    invoiceEmail: "AP_INBOX@MOHEGANSUN.COM",
    route: "MRS ROUTE 21",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Neuehouse': {
    freshbooksId: "345931",
    invoiceEmail: "Convene-HQ-Openings@inbox.docuphase.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Otherside Wine Bar': {
    freshbooksId: "286347",
    invoiceEmail: "team@southdowncoffee.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Parlour Room': {
    freshbooksId: "319719",
    invoiceEmail: "flhgrp@documents.restaurant365.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Pattin\' Restaurant': {
    freshbooksId: "350291",
    invoiceEmail: null,
    route: "NU1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Pinky Swear': {
    freshbooksId: "334007",
    invoiceEmail: "jade@deviledeggsaccounting.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Provisions Sag Harbor': {
    freshbooksId: "116803",
    invoiceEmail: "contact@provisionsnaturalfoods.com",
    route: "R31 NL-117",
    distributor: "FS",
    packaging: "Plastic Retail",
    active: true,
  },
  'Public Hotel': {
    freshbooksId: "171932",
    invoiceEmail: "ny-ap@publichotels.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Ren Sample': {
    freshbooksId: null,
    invoiceEmail: null,
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Plastic Retail",
    active: true,
  },
  'Renaissance Allentown Hotel': {
    freshbooksId: "345375",
    invoiceEmail: null,
    route: "B6",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Seiren': {
    freshbooksId: "350467",
    invoiceEmail: "elvis@chicadon.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Southdown Coffee - Glen Cove': {
    freshbooksId: "299259",
    invoiceEmail: "team@southdowncoffee.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Southdown Coffee - Huntington': {
    freshbooksId: "299083",
    invoiceEmail: "team@southdowncoffee.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Southdown Coffee - Northport': {
    freshbooksId: "299261",
    invoiceEmail: "team@southdowncoffee.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Southdown Coffee - Oyster Bay': {
    freshbooksId: "299081",
    invoiceEmail: "team@southdowncoffee.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Southdown Coffee - Patchogue': {
    freshbooksId: "234167",
    invoiceEmail: "team@southdowncoffee.com",
    route: "R30 NL-223",
    distributor: "FS",
    packaging: "Wholesale",
    active: true,
  },
  'Southdown Coffee - Point Lookout': {
    freshbooksId: "284085",
    invoiceEmail: "team@southdowncoffee.com",
    route: "Route 11 Tony",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Southdown Coffee - Port Jefferson': {
    freshbooksId: "228062",
    invoiceEmail: "team@southdowncoffee.com",
    route: "MRS Rte 32",
    distributor: "MRS",
    packaging: "Wholesale",
    active: true,
  },
  'Stephen Sample': {
    freshbooksId: null,
    invoiceEmail: null,
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Plastic Retail",
    active: true,
  },
  'Stocked by Three Owls': {
    freshbooksId: "356957",
    invoiceEmail: null,
    route: "LI",
    distributor: "ALLNP",
    packaging: "Plastic Retail",
    active: true,
  },
  'Sweet Jane': {
    freshbooksId: "251892",
    invoiceEmail: "sweetjanebookkeeper@gmail.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "Plastic",
    active: true,
  },
  'The Hen House': {
    freshbooksId: "255750",
    invoiceEmail: "Info@henhousenyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'The Parkgate': {
    freshbooksId: "338241",
    invoiceEmail: "ciaran@theparkgatenyc.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'The Shelby': {
    freshbooksId: "326675",
    invoiceEmail: "purchasing@the-shelby.com",
    route: "B6",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'The Standard': {
    freshbooksId: "330411",
    invoiceEmail: "lgash-smb-shlap@standardhotels.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Topping Rose': {
    freshbooksId: "256740",
    invoiceEmail: "jfromm@toppingrosehouse.com",
    route: "R31 NL-107",
    distributor: "FS",
    packaging: "Wholesale",
    active: true,
  },
  'Two Hands - NoHo': {
    freshbooksId: "266324",
    invoiceEmail: "invoices+twohands@dineaccounting.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Two Hands - Tribeca': {
    freshbooksId: "266322",
    invoiceEmail: "invoices+twohands@dineaccounting.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Two Hands - Williamsburg': {
    freshbooksId: "266323",
    invoiceEmail: "invoices+twohands@dineaccounting.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Waldorf Astoria': {
    freshbooksId: "333289",
    invoiceEmail: "NYCWA-AP@waldorfastoria.com",
    route: "B1",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Wall Street Hotel': {
    freshbooksId: "235361",
    invoiceEmail: "edouard@ozaneaux.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "Wholesale",
    active: true,
  },
  'Westhampton Market': {
    freshbooksId: null,
    invoiceEmail: null,
    route: "R31 NL-219",
    distributor: "FS",
    packaging: "Wholesale",
    active: true,
  },
  'Westville - Chelsea': {
    freshbooksId: "307727",
    invoiceEmail: "accounting@westville.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - Dumbo': {
    freshbooksId: "307729",
    invoiceEmail: "accounting@westville.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - East': {
    freshbooksId: "307731",
    invoiceEmail: "accounting@westville.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - Hells Kitchen': {
    freshbooksId: "307733",
    invoiceEmail: "accounting@westville.com",
    route: "NU1",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - Hudson': {
    freshbooksId: "307737",
    invoiceEmail: "accounting@westville.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - LIC': {
    freshbooksId: "314119",
    invoiceEmail: "accounting@westville.com",
    route: "LI",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - Prep Kitchen (Wall St)': {
    freshbooksId: "330021",
    invoiceEmail: "accounting@westville.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - UES': {
    freshbooksId: "347473",
    invoiceEmail: "accounting@westville.com",
    route: "ZAB",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - Upper West Side': {
    freshbooksId: "307739",
    invoiceEmail: "accounting@westville.com",
    route: "ZAB",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - Wall St': {
    freshbooksId: "307735",
    invoiceEmail: "accounting@westville.com",
    route: "B2",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Westville - Williamsburg': {
    freshbooksId: "307563",
    invoiceEmail: "accounting@westville.com",
    route: "BU2",
    distributor: "ALLNP",
    packaging: "PLASTIC",
    active: true,
  },
  'Wolffer': {
    freshbooksId: "42655",
    invoiceEmail: "accountspayable@wolffer.com",
    route: "R41 NL-156",
    distributor: "FS",
    packaging: "Plastic Retail",
    active: true,
  },
}

// Helper: look up client data by name (case-insensitive)
export function lookupClient(name: string) {
  const key = Object.keys(CLIENT_MASTER).find(
    k => k.toLowerCase() === name.toLowerCase()
  )
  return key ? CLIENT_MASTER[key] : null
}