import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/firebase'
import { collection, getDocs, updateDoc, doc } from 'firebase/firestore'

// Full slicing data from CSV: customerName -> { productId -> slicingType }
const SLICING_DATA: Record<string, Record<string, string>> = {
  "Alidoro Bryant Park": {"semolina": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Almond": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Banter - Greenwich Village": {"brioche-pullman-large": "TH Sliced", "mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Banter - Murray Hill": {"brioche-pullman-large": "TH Sliced", "mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Banter - West Village": {"brioche-pullman-large": "TH Sliced", "mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Bird on the Roof MTK": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Bonfire Coffeehouse": {"mb-large": "TH Sliced", "mg-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Bounce Beach": {"bun-large-hamburger": "Sliced", "brioche-pullman-large": "TH Sliced", "semolina": "Sliced", "bun-plain": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Briarcliff": {"sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Carriage House": {"brioche-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Cavaniola's - Amagansett": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Cavaniola's - Sag Harbor": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Chef Jojo's Cookshop": {"semolina": "TH Sliced", "rye-retail": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Chica & The Don": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Coastal Kitchen": {"rye-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Coopers Beach Snack Shack": {"sd-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Cove Hollow": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Creek Club": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Croft SoHo": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Dream Downtown": {"mb-large": "TH Sliced", "mg-large": "Sliced", "large-batard": "TH Sliced", "ww-sandwich": "Sliced", "white-sandwich": "Sliced"},
  "Dudley's": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "East Village Boris & Horton": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Eastport General Store": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Edition Times Square": {"rye-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Evelyn Hotel": {"brioche-pullman-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Falu House": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "sd-batard": "Sliced"},
  "Food Garden Market": {"mg-large": "TH Sliced", "sd-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Frankie's Diner": {"mb-large": "TH Sliced", "large-batard": "Sliced"},
  "FreshDirect": {"semolina": "TH Sliced", "mb-retail": "Sliced", "mg-retail": "TH Sliced", "sd-batard-seeded": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "FreshDirect 2": {"semolina": "TH Sliced", "mb-retail": "Sliced", "mg-retail": "TH Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "GK - Commissary": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "GNF -MT KISKO": {"sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Gertrude's": {"large-batard": "TH Sliced"},
  "Google": {"brioche-pullman-large": "TH Sliced", "mb-large": "TH Sliced", "sd-boule-large-orig": "Sliced", "large-batard": "TH Sliced"},
  "Grey Dog - Chelsea": {"large-batard": "TH Sliced", "mg-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Grey Dog - Columbus Circle": {"large-batard": "TH Sliced", "mg-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Grey Dog - Flatiron": {"large-batard": "TH Sliced", "mg-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Grey Dog - Nolita": {"large-batard": "TH Sliced", "mg-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Grey Dog - Union Square": {"large-batard": "TH Sliced", "mg-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Grey Dog - West Village": {"large-batard": "TH Sliced", "mg-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Gurneys Montauk": {"brioche-pullman-large": "Sliced", "mg-large": "Sliced", "sd-pullman-large": "Sliced", "ww-sandwich": "Sliced"},
  "Hampton Racquet": {"mb-large": "TH Sliced", "mg-large": "Sliced"},
  "Hamptons Aristocrat": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Holy Cow - Elmont": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced"},
  "Holy Cow - Jersey City": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced"},
  "Holy Cow - Midtown": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced"},
  "Holy Cow - Mt Vernon": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced"},
  "Holy Cow - Oakland Gardens": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced"},
  "Holy Cow - Parkchester": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced"},
  "Holy Cow - Piscataway": {"bun-plain": "Sliced"},
  "Holy Cow - Woodland Park": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced"},
  "Hudson National Golf Club": {"brioche-pullman-large": "TH Sliced", "rye-large": "TH Sliced", "mb-large": "TH Sliced", "mg-large": "TH Sliced", "large-batard": "TH Sliced", "sd-pullman-large": "TH Sliced", "sd-boule-large-orig": "TH Sliced", "sd-batard": "TH Sliced"},
  "Jamesport Vineyards": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ketchy Beach": {"bun-large-hamburger": "Sliced", "brioche-pullman-large": "TH Sliced", "bun-plain": "Sliced", "sd-batard-seeded": "TH Sliced", "sd-boule-large-seeded": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ketchy Shuby": {"brioche-pullman-large": "TH Sliced", "mb-large": "TH Sliced", "bun-plain": "Sliced", "large-batard": "TH Sliced", "sd-batard-seeded": "TH Sliced", "sd-batard": "TH Sliced", "bun-sesame-seeded": "Sliced", "mb-4in-burger-bun": "TH Sliced"},
  "Kontokosta Winery": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Le Bilboquet 60th Street": {"mg-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Le Bilboquet Sag Harbor": {"mg-retail": "TH Sliced", "mg-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Legasea": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Libby Sample": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Macari Vineyards": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Maman - 18th Street": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - 55th & Madison": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Ardmore": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Battery Park": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Broadway": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Bryant Park": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Cobble Hill": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Grand Central": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Greenpoint": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Greenwich": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Hudson": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Jersey City": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - King": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Lexington": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Lincoln Square": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Long Island City": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Meatpacking": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Midtown East": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Moynihan Station": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Nomad": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Princeton": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Rockefeller": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Soho": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - The Hugh": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Tribeca": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Upper East Side": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Upper West Side": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Washington Square": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Maman - Westport": {"mb-large": "TH Sliced", "large-batard": "TH Sliced", "mg-batard": "TH Sliced"},
  "Michael Jordan Steakhouse": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Mobys": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun": {"rye-large": "TH Sliced", "sd-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun - Club Lounge": {"brioche-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun - Earth Lounge": {"brioche-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "sd-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun - Sky Bakeshop": {"brioche-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun - Sportsbook 2": {"rye-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun - Todd English": {"sd-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun - Todd English 2": {"sd-pullman-large": "TH Sliced", "sd-batard-seeded": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Mohegan Sun - Todd English Tuscany": {"brioche-pullman-large": "TH Sliced", "sd-pullman-large": "TH Sliced", "sd-batard-seeded": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Motel Morris": {"semolina": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "NGF - Briarcliff": {"sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Nick & Toni's": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Otherside Wine Bar": {"mg-large": "Sliced"},
  "Parlour Room": {"large-batard": "TH Sliced", "mb-large": "Sliced"},
  "Paumanok Vineyards": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Provisions Sag Harbor": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Provisions Water Mill": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Public Hotel": {"sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Quaker Ridge Golf Club": {"brioche-pullman-large": "Sliced", "rye-large": "Sliced", "mb-large": "TH Sliced", "mg-large": "Sliced", "sd-pullman-large": "Sliced", "sd-batard": "Sliced", "large-batard": "TH Sliced"},
  "Quogue Country Market": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R01 J-2832 BRONZE": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R01 J-2832 IVORY": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R02 J-2832 BROWN": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R02 J-2832 TAN": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R02 J-2978": {"mb-retail": "Sliced", "mg-retail": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2079": {"mb-retail": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2088": {"brioche-pullman-large": "Sliced", "mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "R05 J-2832": {"brioche-pullman-retail": "Sliced", "semolina": "Sliced", "rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-batard-seeded": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "sd-batard": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 AMBER": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 BURGUNDY": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 CRIMSON": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 EMERALD": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 GREY": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 PINK": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 PLATINUM": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2832 SCARLETT": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R05 J-2979": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R09 J-100": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-batard": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R09 J-102": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "sd-batard": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R12 J-552": {"large-batard": "TH Sliced", "sd-batard": "Sliced", "mb-large": "TH Sliced"},
  "R18 A0087247": {"rye-retail": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R22 A0063204": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "R31 J-9060": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "R31 J-9078": {"rye-large": "TH Sliced", "mg-large": "TH Sliced", "sd-pullman-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R31 J-9115": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "R32 J-9084": {"sd-batard": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R33 J-9000": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "R33 J-9021": {"mg-large": "Sliced", "sd-pullman-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R33 J-9038": {"rye-retail": "Sliced", "mb-retail": "Sliced", "mg-retail": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R33 J-9080": {"mg-large": "Sliced", "sd-pullman-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "R35 J-108": {"brioche-pullman-large": "TH Sliced", "mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "R35 J-3016": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "R36 J-9084": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ren Sample": {"brioche-pullman-large": "TH Sliced", "rye-large": "TH Sliced", "mg-large": "TH Sliced", "mg-batard": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Renaissance Allentown Hotel": {"rye-large": "Sliced", "mb-large": "Sliced", "mg-large": "Sliced", "mb-4in-burger-bun": "Sliced"},
  "Rexer Family Farm": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Rocco's": {"mb-retail": "TH Sliced", "mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Rose Hill Vineyards": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ruby's - East Village": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ruby's - Greenwich": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ruby's - Murray Hill": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ruby's - SoHo": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ruby's - West Village": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Ruby's - Williamsburg": {"large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "Sliced"},
  "Sample 1": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Sample 2": {"rye-large": "Sliced", "mb-retail": "Sliced", "sd-batard-seeded": "Sliced", "sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Sample 3": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Schmidt's Market": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Seiren": {"mb-large": "Sliced"},
  "Si Si": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Southampton Golf Club": {"brioche-pullman-large": "TH Sliced", "mb-large": "TH Sliced", "mg-large": "TH Sliced", "large-batard": "TH Sliced", "sd-pullman-large": "TH Sliced", "sd-batard-seeded": "TH Sliced", "sd-batard": "TH Sliced"},
  "Southdown Coffee - Glen Cove": {"mb-large": "TH Sliced", "mg-large": "Sliced", "large-batard": "TH Sliced", "sd-batard": "Sliced"},
  "Southdown Coffee - Huntington": {"mb-large": "TH Sliced", "mg-large": "Sliced", "large-batard": "TH Sliced", "sd-batard": "Sliced"},
  "Southdown Coffee - Northport": {"mg-large": "Sliced", "large-batard": "TH Sliced", "sd-batard": "Sliced", "mb-large": "TH Sliced"},
  "Southdown Coffee - Oyster Bay": {"mg-large": "Sliced", "large-batard": "TH Sliced", "sd-batard": "Sliced", "mb-large": "TH Sliced"},
  "Southdown Coffee - Patchogue": {"mg-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Southdown Coffee - Point Lookout": {"mg-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Southdown Coffee - Port Jefferson": {"mg-large": "Sliced", "large-batard": "TH Sliced", "sd-batard": "Sliced", "mb-large": "TH Sliced"},
  "Southdown Marketplace - Huntington": {"sd-batard": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Stephen Sample": {"white-bread-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Stocked by Three Owls": {"mb-retail": "Sliced", "mg-retail": "Sliced"},
  "Surf Lodge": {"bun-large-hamburger": "Sliced", "bun-plain": "Sliced", "large-batard": "TH Sliced", "sd-batard": "TH Sliced", "bun-sesame-seeded": "Sliced", "mb-4in-burger-bun": "Sliced", "mb-large": "TH Sliced"},
  "The Hen House": {"mb-4in-burger-bun": "Sliced"},
  "The Manner": {"mg-large": "Sliced", "sd-pullman-large": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "The Parkgate": {"large-batard": "Sliced"},
  "The Shelby": {"brioche-pullman-large": "TH Sliced", "mg-large": "TH Sliced", "large-batard": "TH Sliced", "sd-pullman-large": "TH Sliced", "mg-batard": "TH Sliced"},
  "The Standard": {"mb-large": "Sliced", "mg-large": "SLICED 1""},
  "The Yacht Club": {"mb-large": "Sliced"},
  "Toastie Land": {"mb-retail": "TH Sliced", "mb-large": "TH Sliced", "sd-pullman-large": "TH Sliced", "white-bread-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Tokeneke Club": {"brioche-pullman-large": "TH Sliced", "rye-large": "TH Sliced", "mb-large": "TH Sliced", "mg-large": "TH Sliced", "sd-pullman-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Topping Rose": {"mg-large": "Sliced", "sd-boule-large-orig": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Two Hands - NoHo": {"large-batard": "TH Sliced", "sd-batard-seeded": "TH Sliced", "sd-boule-large-seeded": "Sliced", "sd-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Two Hands - Nolita": {"large-batard": "TH Sliced", "sd-batard-seeded": "TH Sliced", "sd-boule-large-seeded": "Sliced", "sd-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Two Hands - Tribeca": {"large-batard": "TH Sliced", "sd-batard-seeded": "TH Sliced", "sd-boule-large-seeded": "Sliced", "sd-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Two Hands - Williamsburg": {"large-batard": "TH Sliced", "sd-batard-seeded": "TH Sliced", "sd-boule-large-seeded": "Sliced", "sd-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "VICTOR SAMPLE": {"sd-boule-large-orig": "Sliced", "sd-boule-large-seeded": "Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Vin Sur Vingt": {"mb-large": "TH Sliced", "large-batard": "TH Sliced"},
  "Waldorf Astoria": {"mb-large": "TH Sliced", "mg-large": "Sliced", "sd-boule-large-orig": "Sliced", "light-rye-sandwich": "Sliced", "ww-sandwich": "Sliced", "white-sandwich": "Sliced"},
  "Wall Street Hotel": {"rye-large": "TH Sliced", "mb-retail": "TH Sliced", "mg-large": "TH Sliced", "large-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Water Mill Center": {"mb-large": "TH Sliced"},
  "Westville - Chelsea": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - Dumbo": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - East": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - Hells Kitchen": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - Hudson": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - LIC": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - UES": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - Upper West Side": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - Wall St": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Westville - Williamsburg": {"mg-batard": "TH Sliced", "large-batard": "TH Sliced", "italian-batard": "TH Sliced", "mb-large": "TH Sliced"},
  "Wolffer": {"large-batard": "TH Sliced", "mb-large": "TH Sliced"},
}

export async function POST(request: NextRequest) {
  try {
    const snap = await getDocs(collection(db, 'customers'))
    let updated = 0
    let skipped = 0
    const skippedNames: string[] = []

    for (const docSnap of snap.docs) {
      const customer = docSnap.data()
      const name = customer.name?.trim()
      if (!name) continue

      // Try exact match first, then case-insensitive
      const slicing = SLICING_DATA[name] ||
        SLICING_DATA[Object.keys(SLICING_DATA).find(k =>
          k.toLowerCase() === name.toLowerCase()
        ) || '']

      if (slicing) {
        await updateDoc(doc(db, 'customers', docSnap.id), { slicing })
        updated++
      } else {
        skipped++
        skippedNames.push(name)
      }
    }

    return NextResponse.json({ success: true, updated, skipped, skippedNames })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
